/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 15-Ene.-2023 02:18:33 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Cuentas_Proyecto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cuentas] DROP CONSTRAINT [FK_Cuentas_Proyecto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Cuentas_TipoCuenta]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cuentas] DROP CONSTRAINT [FK_Cuentas_TipoCuenta]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Cuentas_Usuario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cuentas] DROP CONSTRAINT [FK_Cuentas_Usuario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Proyecto_EstadoProyecto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Proyecto] DROP CONSTRAINT [FK_Proyecto_EstadoProyecto]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cuentas]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cuentas]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[EstadoProyecto]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [EstadoProyecto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Proyecto]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Proyecto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TipoCuenta]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TipoCuenta]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Usuario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Usuario]
GO

/* Create Tables */

CREATE TABLE [Cuentas]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[TipoCuenta_Id] int NULL,
	[Sitio] varchar(1000) NULL,
	[Usuario] varchar(50) NULL,
	[Password] varchar(50) NULL,
	[Usuario_Id] int NULL,
	[Proyecto_Id] int NULL,
	[FechaCreacion] datetime NULL,
	[UsuarioCrea] int NULL,
	[FechaModificacion] datetime NULL,
	[UsuarioModificacion] int NULL
)
GO

CREATE TABLE [EstadoProyecto]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[Estado] bit NULL,
	[Descripcion] varchar(50) NULL,
	[FechaCreacion] datetime NULL,
	[UsuarioCrea] int NULL,
	[FechaModificacion] datetime NULL,
	[UsuarioModifica] int NULL
)
GO

CREATE TABLE [Proyecto]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[Descripcion] varchar(50) NULL,
	[EstadoProyecto_Id] int NULL,
	[UsuarioCrea] int NULL,
	[FechaCreacion] datetime NULL,
	[UsuarioModifica] int NULL,
	[FechaModificacion] datetime NULL
)
GO

CREATE TABLE [TipoCuenta]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[Descripcion] varchar(50) NULL,
	[Estado] bit NULL,
	[UsuarioCreacion] int NULL,
	[FechaCreacion] datetime NULL,
	[UsuarioModificacion] int NULL,
	[FechaModificacion] datetime NULL
)
GO

CREATE TABLE [Usuario]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[Usuario] varchar(50) NULL,
	[Password] varchar(1025) NULL,
	[FechaCreacion] datetime NULL,
	[UsuarioCreacion] int NULL,
	[FechaModificacion] datetime NULL,
	[UsuarioModificacion] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Cuentas] 
 ADD CONSTRAINT [PK_Cuentas]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [EstadoProyecto] 
 ADD CONSTRAINT [PK_EstadoProyecto]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Proyecto] 
 ADD CONSTRAINT [PK_Proyecto]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [TipoCuenta] 
 ADD CONSTRAINT [PK_TipoCuenta]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Usuario] 
 ADD CONSTRAINT [PK_Usuario]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Cuentas] ADD CONSTRAINT [FK_Cuentas_Proyecto]
	FOREIGN KEY ([Proyecto_Id]) REFERENCES [Proyecto] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Cuentas] ADD CONSTRAINT [FK_Cuentas_TipoCuenta]
	FOREIGN KEY ([TipoCuenta_Id]) REFERENCES [TipoCuenta] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Cuentas] ADD CONSTRAINT [FK_Cuentas_Usuario]
	FOREIGN KEY ([Usuario_Id]) REFERENCES [Usuario] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Proyecto] ADD CONSTRAINT [FK_Proyecto_EstadoProyecto]
	FOREIGN KEY ([EstadoProyecto_Id]) REFERENCES [EstadoProyecto] ([Id]) ON DELETE No Action ON UPDATE No Action
GO
